apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgpool.fullname" . }}
  labels:
    {{- include "pgpool.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgpool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgpool.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pgpool
              containerPort: 5432
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: pgpool
          readinessProbe:
            tcpSocket:
              port: pgpool
          env:
            - name: PGPOOL_ADMIN_USERNAME
              value: {{ .Values.adminUsername | quote }}
            - name: PGPOOL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "pgpool.fullname" . }}
                  key: admin-password
            - name: PGPOOL_HEALTH_CHECK_PERIOD
              value: "0" # 0 means health check disabled, bitnami image will refuse to load without hc user and password still:
            {{ if not (empty .Values.healthCheckSecret) }}
            - name: PGPOOL_HEALTH_CHECK_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.healthCheckSecret }}
                  key: {{ .Values.healthCheckSecretUsernameField }}
            - name: PGPOOL_HEALTH_CHECK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.healthCheckSecret }}
                  key: {{ .Values.healthCheckSecretPasswordField }}
            - name: PGPOOL_SR_CHECK_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.healthCheckSecret }}
                  key: {{ .Values.healthCheckSecretUsernameField }}
            - name: PGPOOL_SR_CHECK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.healthCheckSecret }}
                  key: {{ .Values.healthCheckSecretPasswordField }}
            {{ else }}
            - name: PGPOOL_HEALTH_CHECK_USER
              value:  {{ .Values.healthCheckUsername | quote }}
            - name: PGPOOL_HEALTH_CHECK_PASSWORD
              value:  {{ .Values.healthCheckPassword | quote }}
            - name: PGPOOL_SR_CHECK_USER
              value: {{ .Values.healthCheckUsername | quote }}
            - name: PGPOOL_SR_CHECK_PASSWORD              
              value:  {{ .Values.healthCheckPassword | quote }}              
            {{ end }}
            - name: PGPOOL_ENABLE_POOL_HBA
              value: "no"              
            - name: PGPOOL_ENABLE_POOL_PASSWD
              value: "no"              
            - name: PGPOOL_BACKEND_NODES
              value: {{ .Values.backends | quote }}
            - name: PGPOOL_SR_CHECK_PERIOD
              value: "0"
            - name: PGPOOL_ENABLE_LOAD_BALANCING
              value: "yes"
            - name: PGPOOL_DISABLE_LOAD_BALANCE_ON_WRITE
              value: "always"
            - name: PGPOOL_NUM_INIT_CHILDREN
              value: {{ .Values.numInitChildren | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
