{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    {{- include "pgpool.labels" . | nindent 4 }}
  name: {{ include "pgpool.fullname" . }}
spec:
  host: {{ include "pgpool.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterName }}
{{- end }}
