apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgpool.fullname" . }}
  labels:
    app: {{ template "pgpool.name" . }}
    chart: {{ template "pgpool.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  admin-password: {{ include "pgpool.password" . | b64enc | quote }}
