# Default values for pgpool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bitnami/pgpool
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


# pgpool admin username & password
adminUsername: admin
# adminPassword:

# postgresql backends:
#backends :"0:pg-0:5432,1:pg-1:5432"
# or with weight for load balancing:
# backends: "0:pg-0:5432:0.3,1:pg-1:5432:0.7"
# or with failover behavior:
  # backends: "0:pg-0:5432:0.3:.:DISALLOW_TO_FAILOVER,1:pg-1:5432:0.7:.:DISALLOW_TO_FAILOVER"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5432


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
