apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-zabbix
  labels:
    app.kubernetes.io/name:  {{ .Release.Name }}-zabbix
    helm.sh/chart: {{ include "zabbix.chart" . }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1 # do not scale!
  selector:
    matchLabels:
      app.kubernetes.io/name:  {{ .Release.Name }}-zabbix
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  {{ .Release.Name }}-zabbix
        release: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}      
      containers:
        - name: zabbix
          image: {{ .Values.zabbix.image.repository }}:{{ .Values.zabbix.image.tag }}
          imagePullPolicy: {{ .Values.zabbix.image.pullPolicy }}
          resources:
            {{- toYaml .Values.zabbix.resources | nindent 12 }}
          ports:
            - name: postgres
              containerPort: 10051
              protocol: TCP
          env:
          - name: DB_SERVER_HOST
            value: {{ .Values.postgresqlHost | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresqlUsername | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresqlPassword | quote }}
        - name: zabbix-agent
          image: {{ .Values.zabbixAgent.image.repository }}:{{ .Values.zabbixAgent.image.tag }}
          imagePullPolicy: {{ .Values.zabbix.image.pullPolicy }}
          resources:
            {{- toYaml .Values.zabbixAgent.resources | nindent 12 }}
          env:
          - name: ZBX_SERVER_HOST
            value: 127.0.0.1
          - name: ZBX_HOSTNAME
            value: {{ .Release.Name }}-zabbix
