kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-zabbix-web
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-zabbix-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 443
    targetPort: 8443
    name: https
