apiVersion: v1
kind: Secret
metadata:
  labels:
    pgo-created-by: bootstrap
    pgo-pgorole: "true"
    rolename: pgoadmin
    vendor: crunchydata
  name: pgorole-pgoadmin
type: Opaque
data:
  permissions: {{ "*" | b64enc | quote }}
  rolename: {{ "pgorole-pgoadmin" | b64enc | quote }}
