# Default values for postgres-ha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
volumeSize: 2Gi
  
resources:
  limits:
    cpu: 1500m
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 100Mi


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


# See Zalando postgres-operator documentation regarding postgresql CRD:
teamId: acid
users: {}
#  zalando:
#    - superuser
#    - createdb

patroni: {}
#  pg_hba:
#  - host  all all 0.0.0.0/0 md5


postgresql:
  version: "12"
#  parameters:
#    log_statement: all
  
