# Default values for postgres-ha.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
volumeSize: 2Gi
  
resources:
  limits:
    cpu: 1500m
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 100Mi


autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


istio:
  enabled: false

clusterName: cluster.local

# give ownership to specific postgres-operator (controllerId):
#operatorId:

# See Zalando postgres-operator documentation regarding postgresql CRD:
teamId: acid
users: {}
#  zalando:
#    - superuser
#    - createdb

patroni:
  pg_hba:  
  - host  all all 0.0.0.0/0 md5
  - hostnossl replication standby all md5 # important for Istio's mTLS


postgresql:
  version: "12"
#  parameters:
#    log_statement: all
  

# Logical Backups:
backup:
  enabled: false
  schedule: "0 0 * * *"
  gcsBucket:
  gcsSvcTokenSecret:
  gcsSvcTokenFileName: "gcskey.json"
  azureStorageAccount:
  azureStorageKey:
  azureStorageContainer:
