apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
    app: {{ template "timescaledb.name" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}
