{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    {{- include "postgres-ha.labels" . | nindent 4 }}
  name: {{ printf "%s-%s"  .Values.teamId .Release.Name }}-repl
spec:
  host: {{ printf "%s-%s"  .Values.teamId .Release.Name }}.{{ .Release.Namespace }}-repl.svc.{{ .Values.clusterName }}
{{- end }}
