apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
      team: {{ .Values.teamId  | quote }}
      app: {{ printf "spilo-%s-%s"  .Values.teamId .Release.Name | quote }}
  annotations:
    {{- if .Values.operatorId }}
    "acid.zalan.do/controller":  {{ .Values.operatorId  | quote }}
    {{- end }}
  name: {{ printf "%s-%s"  .Values.teamId .Release.Name | quote }}
spec:
    numberOfInstances: {{ .Values.replicaCount }}
    patroni:
      {{- toYaml .Values.patroni | nindent 6 }}
    postgresql:
      {{- toYaml .Values.postgresql | nindent 6 }}
    resources:
      {{- toYaml .Values.resources | nindent 8 }}
    teamId: {{ .Values.teamId | quote }}
    users:
      {{- toYaml .Values.users | nindent 6 }}
    volume:
      size: {{ .Values.volumeSize }}
